spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
              - JwtAuthenticationFilter
        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
          filters:
            - JwtAuthenticationFilter
        - id: categories-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/categories/**
          filters:
            - JwtAuthenticationFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
          filters:
            - JwtAuthenticationFilter
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - JwtAuthenticationFilter
      globals:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowCredentials: true
        csrf:
          enabled: false

  application:
    name: api-gateway

  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/keys

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

application:
  jwtExpirationMs: 86400000

logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG

jwt:
  secret: ThisIsASecretKeyOfPhuTam54

authentication:
  enabled: true